root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go tool templ generate && go build -o ./tmp/main ./main.go"
delay = 1000
exclude_dir = ["static", "tmp", "vendor", "testdata"]
exclude_file = ["**/*_templ.go"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
full_bin = "GO_ENV=development ./tmp/main"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_file = []
kill_delay = "10s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
