# fly.toml app configuration file generated for share-dev-shy-resonance-7378 on 2025-08-20T22:29:30-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'share-dev'
primary_region = 'phx'

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ['run-app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
