create schema if not exists rbac;
grant usage on schema rbac to supabase_auth_admin;
grant usage on schema public to supabase_auth_admin;

-- Create Roles tables
do $$
begin
create table if not exists rbac.roles (
  id bigint generated by default as identity primary key,
  role text UNIQUE NOT NULL
);
comment on table rbac.roles is 'RBAC Roles for Application.';
end $$;

do $$
begin
insert into rbac.roles (role) values
  ('user'),
  ('admin'),
  ('super')
on conflict do nothing;
end $$;

-- Create Permission Enum
-- Permissions style 'action:resource:[optional]modifier', should just be strings tho ...
-- | =================================== |
-- | Modifider in use:                   |
-- | self    : resources owned by a user |
-- | friends : friends can see this data |
-- | global  : open to the public        |
-- | =================================== |
do $$
begin
create table if not exists rbac.permissions (
  id bigint generated by default as identity primary key,
  permission text UNIQUE NOT NULL
);
comment on table rbac.permissions is 'RBAC Permissions for Application.';
insert into rbac.permissions (permission) values
  -- Posts
  ('create:post'),
  ('read:post'),
  ('update:post:self'),
  ('delete:post:self'),
  ('delete:post:any'),
  -- Comments
  ('create:comment'),
  ('read:comment'),
  ('update:comment:self'),
  ('delete:comment:self'),
  ('delete:comment:any'),
  -- Likes
  ('create:like'),
  ('read:like'),
  ('delete:like:self'),
  -- Follows
  ('create:follow'),
  ('read:follow'),
  ('delete:follow'),
  -- Profiles
  ('read:profile'),
  ('update:profile:self'),
  -- Roles
  ('read:roles'),
  -- ('update:roles'),
  -- User Roles
  ('read:user_roles'),
  ('update:user_roles'),
  ('all:*:super') -- super user access
on conflict do nothing;
end $$;

do $$
begin
create table if not exists rbac.user_roles (
  -- id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      text references rbac.roles(role) on delete cascade not null,
  primary key (user_id, role)
  -- unique (user_id, role)
);
comment on table rbac.user_roles is 'Application roles for each user.';
end $$;

do $$
begin
create table if not exists rbac.role_permissions (
  -- id bigint generated by default as identity primary key,
  role text references rbac.roles(role) on delete cascade not null,
  permission text references rbac.permissions(permission) on delete cascade not null,
  primary key (role, permission)
);
comment on table rbac.role_permissions is 'Application permissions for each role.';
end $$;
-- Insert role_permissions for rbac.role_permissions
do $$
begin
-- USER role
insert into rbac.role_permissions (role, permission) values
  ('user', 'create:comment'),
  ('user', 'read:comment'),
  ('user', 'update:comment:self'),
  ('user', 'delete:comment:self'),

  ('user', 'create:follow'),
  ('user', 'read:follow'),
  ('user', 'delete:follow'),

  ('user', 'create:like'),
  ('user', 'read:like'),
  ('user', 'delete:like:self'),

  ('user', 'create:post'),
  ('user', 'read:post'),
  ('user', 'update:post:self'),
  ('user', 'delete:post:self'),

  ('user', 'read:profile'),
  ('user', 'update:profile:self')
on conflict do nothing;
end $$;

do $$
begin
-- ADMIN role (inherits user, plus can delete:any post/comment)
insert into rbac.role_permissions (role, permission) values
  ('admin', 'create:comment'),
  ('admin', 'read:comment'),
  ('admin', 'update:comment:self'),
  ('admin', 'delete:comment:self'),
  ('admin', 'delete:comment:any'),

  ('admin', 'create:follow'),
  ('admin', 'read:follow'),
  ('admin', 'delete:follow'),

  ('admin', 'create:like'),
  ('admin', 'read:like'),
  ('admin', 'delete:like:self'),

  ('admin', 'create:post'),
  ('admin', 'read:post'),
  ('admin', 'update:post:self'),
  ('admin', 'delete:post:self'),
  ('admin', 'delete:post:any'),

  ('admin', 'read:profile'),
  ('admin', 'update:profile:self'),

  ('admin', 'read:roles'),
  -- ('admin', 'update:roles'),

  ('admin', 'read:user_roles'),
  ('admin', 'update:user_roles')
on conflict do nothing;
end $$;

do $$
begin
-- SUPER role (inherits admin, all permissions)
insert into rbac.role_permissions (role, permission) values
  ('super', 'create:comment'),
  ('super', 'read:comment'),
  ('super', 'update:comment:self'),
  ('super', 'delete:comment:self'),
  ('super', 'delete:comment:any'),

  ('super', 'create:follow'),
  ('super', 'read:follow'),
  ('super', 'delete:follow'),

  ('super', 'create:like'),
  ('super', 'read:like'),
  ('super', 'delete:like:self'),

  ('super', 'create:post'),
  ('super', 'read:post'),
  ('super', 'update:post:self'),
  ('super', 'delete:post:self'),
  ('super', 'delete:post:any'),

  ('super', 'read:profile'),
  ('super', 'update:profile:self'),

  ('super', 'read:roles'),
  -- ('super', 'update:roles'),

  ('super', 'read:user_roles'),
  ('super', 'update:user_roles'),

  -- super passthru
  ('super', 'all:*:super')
on conflict do nothing;
end $$;

-- Create the auth hook function
create or replace function rbac.custom_access_token_hook(event jsonb)
returns jsonb as $$
  declare
    claims jsonb;
    user_roles jsonb;
  begin
    -- Aggregate all roles for the user into a JSONB array
    select jsonb_agg(role) into user_roles from rbac.user_roles where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_roles is not null then
      -- Set the nested roles array in claims under user_metadata
      claims := jsonb_set(claims, '{user_metadata,roles}', user_roles, true);
    end if;

    -- Update the 'claims' field in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the updated event JSONB
    return event;
  end;
$$ language plpgsql set search_path = '';


grant execute
  on function rbac.custom_access_token_hook
  to supabase_auth_admin;
revoke execute
  on function rbac.custom_access_token_hook
  from authenticated, anon, public;
grant all
  on table rbac.user_roles
  to supabase_auth_admin;
revoke all
  on table rbac.user_roles
  from authenticated, anon, public;
create policy "Allow auth admin to read user roles" ON rbac.user_roles
  as permissive for select
  to supabase_auth_admin
  using (true);

create or replace function rbac.authorize(
  requested_permission rbac.permissions
)
returns boolean as $$
begin
  return exists (
    select 1
      from rbac.user_roles ur
      join rbac.role_permissions rp on ur.role = rp.role
     where ur.user_id = auth.uid()
       and rp.permission = requested_permission
  );
end;
$$ language plpgsql set search_path = '';
-- example of using function with rls
-- create policy "Allow authorized delete access" on public.channels for delete to authenticated using ( (SELECT authorize('channels.delete')) );
-- create policy "Allow authorized delete access" on public.messages for delete to authenticated using ( (SELECT authorize('messages.delete')) );

create or replace function rbac.make_user_role()
returns trigger as $$
begin
  insert into rbac.user_roles (user_id, role)
  values (new.id, 'user');
  return new;
end;
$$ language plpgsql set search_path = '';

drop trigger if exists make_user_role on auth.users;
create trigger make_user_role
  after insert on auth.users
  for each row execute procedure rbac.make_user_role();
