-- Return a bool if enum exists
create or replace function enum_exists(enum_name text, enum_schema text default 'public')
returns boolean
language sql
as $$
  select exists (
    select 1
    from pg_type t
    join pg_namespace n on t.typnamespace = n.oid
        where t.typname = enum_name
          and n.nspname = enum_schema
    );
$$;

create or replace function table_exists(table_name text, schema_name text default 'public')
returns boolean
language sql
as $$
  select exists (
    select 1
    from pg_tables
    where schemaname = schema_name
      and tablename = table_name
  );
$$;

-- Create Roles Enum
do $$
begin
if not enum_exists('app_role') then
  create type public.app_role as enum ('user', 'admin', 'super');
-- else
  -- alter type public.app_role rename value 'super' to 'super-user';
  -- alter type app_role add value 'people-places-things';

  -- alter type app_role rename value 'pending' to 'waiting';

  -- drop type app_role;
end if;
end $$;

-- Create Permission Enum
-- Permissions style 'action:resource:[optional]modifier', should just be strings tho ...
-- | =================================== |
-- | Modifider in use:                   |
-- | self    : resources owned by a user |
-- | friends : friends can see this data |
-- | global  : open to the public        |
-- | =================================== |
do $$
begin
if not enum_exists('app_permission') then
  create type public.app_permission as enum (
      'create:post:friends' -- (?)
      ,'create:post:global' -- (?)
      ,'read:post'
      ,'update:post:self'
      ,'delete:post:self'
    );
  -- else
  -- drop type public.app_permission;
end if;
end $$;

do $$
begin
if not table_exists('user_roles') THEN
  create table public.user_roles (
    id        bigint generated by default as identity primary key,
    user_id   uuid references auth.users on delete cascade not null,
    role      app_role not null,
    unique (user_id, role)
  );
  comment on table public.user_roles is 'Application roles for each user.';
end if;
end $$;

do $$
begin
if not table_exists('role_permissions') then
  create table public.role_permissions (
    id bigint generated by default as identity primary key,
    role app_role not null,
    permission app_permission not null,
    UNIQUE (role, permission)
  );
  comment on table public.role_permissions is 'Application permissions for each role.';
end if;
end $$;

-- insert into public.role_permissions (role, permission)
-- VALUES
-- (),
-- ();

-- Create the auth hook function
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
  declare
    claims jsonb;
    user_roles jsonb;
  begin
    -- Aggregate all roles for the user into a JSONB array
    select jsonb_agg(role) into user_roles from public.user_roles where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_roles is not null then
      -- Set the nested roles array in claims under user_metadata
      claims := jsonb_set(claims, '{user_metadata,roles}', user_roles, true);
    end if;

    -- Update the 'claims' field in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the updated event JSONB
    return event;
  end;
$$;

grant usage on schema public to supabase_auth_admin;
grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;
revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon, public;
grant all
  on table public.user_roles
to supabase_auth_admin;
revoke all
  on table public.user_roles
  from authenticated, anon, public;
create policy "Allow auth admin to read user roles" ON public.user_roles
as permissive for select
to supabase_auth_admin
using (true);

create or replace function public.authorize(
  requested_permission app_permission
)
returns boolean
as $$
declare
  bind_permissions int;
  user_role public.app_role;
begin
  -- Fetch user role once and store it to reduce number of calls
  select (auth.jwt() ->> 'user_role')::public.app_role into user_role;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$$ language plpgsql stable security definer set search_path = '';

-- example of using function with rls
-- create policy "Allow authorized delete access" on public.channels for delete to authenticated using ( (SELECT authorize('channels.delete')) );
-- create policy "Allow authorized delete access" on public.messages for delete to authenticated using ( (SELECT authorize('messages.delete')) );
